[build]
  command = "node scripts/write-config.js"
  publish = "site"

[build.environment]
  NODE_VERSION = "20"

[functions]
  [functions."publish"]
    timeout = 26

[[edge_functions]]
  function = "images"
  path = "/*"
